# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

#Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
   
# Setup
title:               FaceTech
tagline:             'Computer Vision, Face Detection, Face Recognition'
description:         'A blog on facial analysis technology' 
url:                 http://facetech.me
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Me
  url:               http://facetech.me
  email:             facetech.me@gmail.com

# Custom vars
version:             1.0.0
